# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Wed Apr 24 03:55:53 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VideoTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.VideoTabs.setGeometry(QtCore.QRect(1, 1, 831, 591))
        self.VideoTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.VideoTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.VideoTabs.setObjectName("VideoTabs")
        self.PreviewRecordTab = QtWidgets.QWidget()
        self.PreviewRecordTab.setObjectName("PreviewRecordTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.PreviewRecordTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 641, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.RecordButton = QtWidgets.QPushButton(self.PreviewRecordTab)
        self.RecordButton.setGeometry(QtCore.QRect(300, 500, 93, 28))
        self.RecordButton.setObjectName("RecordButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.PreviewRecordTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(660, 10, 161, 481))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PR_OptionsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.PR_OptionsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.PR_OptionsLabel.setObjectName("PR_OptionsLabel")
        self.verticalLayout_3.addWidget(self.PR_OptionsLabel)
        self.Camera1Checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Camera1Checkbox.setObjectName("Camera1Checkbox")
        self.verticalLayout_3.addWidget(self.Camera1Checkbox)
        self.Camera2Checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Camera2Checkbox.setObjectName("Camera2Checkbox")
        self.verticalLayout_3.addWidget(self.Camera2Checkbox)
        self.Camera3Checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Camera3Checkbox.setObjectName("Camera3Checkbox")
        self.verticalLayout_3.addWidget(self.Camera3Checkbox)
        self.Camera4Checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Camera4Checkbox.setObjectName("Camera4Checkbox")
        self.verticalLayout_3.addWidget(self.Camera4Checkbox)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PR_OptionsApplyButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.PR_OptionsApplyButton.setObjectName("PR_OptionsApplyButton")
        self.horizontalLayout_2.addWidget(self.PR_OptionsApplyButton)
        self.PR_OptionsCancelButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.PR_OptionsCancelButton.setObjectName("PR_OptionsCancelButton")
        self.horizontalLayout_2.addWidget(self.PR_OptionsCancelButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.VideoTabs.addTab(self.PreviewRecordTab, "")
        self.PlaybackTab = QtWidgets.QWidget()
        self.PlaybackTab.setObjectName("PlaybackTab")
        self.PlaybackVideoFrame = QtWidgets.QFrame(self.PlaybackTab)
        self.PlaybackVideoFrame.setGeometry(QtCore.QRect(9, 9, 640, 480))
        self.PlaybackVideoFrame.setObjectName("PlaybackVideoFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PlaybackVideoFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlaybackVideo = QtWidgets.QLabel(self.PlaybackVideoFrame)
        self.PlaybackVideo.setText("")
        self.PlaybackVideo.setObjectName("PlaybackVideo")
        self.verticalLayout.addWidget(self.PlaybackVideo)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.PlaybackTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 490, 641, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RewindButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RewindButton.setObjectName("RewindButton")
        self.horizontalLayout.addWidget(self.RewindButton)
        self.PlayPauseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PlayPauseButton.setObjectName("PlayPauseButton")
        self.horizontalLayout.addWidget(self.PlayPauseButton)
        self.StopButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StopButton.setObjectName("StopButton")
        self.horizontalLayout.addWidget(self.StopButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.PlaybackTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(660, 10, 160, 481))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PB_OptionsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.PB_OptionsLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.PB_OptionsLabel.setObjectName("PB_OptionsLabel")
        self.verticalLayout_4.addWidget(self.PB_OptionsLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.VideoInputLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.VideoInputLabel.setObjectName("VideoInputLabel")
        self.verticalLayout_4.addWidget(self.VideoInputLabel)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.PB_BrowseButtonOne = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.PB_BrowseButtonOne.setMaximumSize(QtCore.QSize(60, 16777215))
        self.PB_BrowseButtonOne.setObjectName("PB_BrowseButtonOne")
        self.verticalLayout_4.addWidget(self.PB_BrowseButtonOne)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.VideoTabs.addTab(self.PlaybackTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.VideoTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.RecordButton.setText(QtWidgets.QApplication.translate("MainWindow", "Record", None, -1))
        self.PR_OptionsLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.Camera1Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Camera 1", None, -1))
        self.Camera2Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Camera 2", None, -1))
        self.Camera3Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Camera 3", None, -1))
        self.Camera4Checkbox.setText(QtWidgets.QApplication.translate("MainWindow", "Camera 4", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Record Time (seconds)", None, -1))
        self.PR_OptionsApplyButton.setText(QtWidgets.QApplication.translate("MainWindow", "Apply", None, -1))
        self.PR_OptionsCancelButton.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel", None, -1))
        self.VideoTabs.setTabText(self.VideoTabs.indexOf(self.PreviewRecordTab), QtWidgets.QApplication.translate("MainWindow", "Preview/Record", None, -1))
        self.RewindButton.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.PlayPauseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Play", None, -1))
        self.StopButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.PB_OptionsLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.VideoInputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Video To Play", None, -1))
        self.PB_BrowseButtonOne.setText(QtWidgets.QApplication.translate("MainWindow", "Browse", None, -1))
        self.VideoTabs.setTabText(self.VideoTabs.indexOf(self.PlaybackTab), QtWidgets.QApplication.translate("MainWindow", "Playback", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))

