# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Sat Mar  2 20:08:44 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 79, 121, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 10, 481, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VideoArea = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.VideoArea.setText("")
        self.VideoArea.setObjectName("VideoArea")
        self.verticalLayout_2.addWidget(self.VideoArea)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(630, 10, 121, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SampleDialogButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleDialogButton.sizePolicy().hasHeightForWidth())
        self.SampleDialogButton.setSizePolicy(sizePolicy)
        self.SampleDialogButton.setObjectName("SampleDialogButton")
        self.verticalLayout_3.addWidget(self.SampleDialogButton)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(139, 450, 481, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RewindButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.RewindButton.setObjectName("RewindButton")
        self.horizontalLayout_2.addWidget(self.RewindButton)
        self.PlayButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PlayButton.setObjectName("PlayButton")
        self.horizontalLayout_2.addWidget(self.PlayButton)
        self.PauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PauseButton.setObjectName("PauseButton")
        self.horizontalLayout_2.addWidget(self.PauseButton)
        self.StopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.StopButton.setObjectName("StopButton")
        self.horizontalLayout_2.addWidget(self.StopButton)
        self.FastForwardButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.FastForwardButton.setObjectName("FastForwardButton")
        self.horizontalLayout_2.addWidget(self.FastForwardButton)
        self.RecordButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.RecordButton.setObjectName("RecordButton")
        self.horizontalLayout_2.addWidget(self.RecordButton)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(630, 79, 121, 411))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 124, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SampleWidgetButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleWidgetButton.sizePolicy().hasHeightForWidth())
        self.SampleWidgetButton.setSizePolicy(sizePolicy)
        self.SampleWidgetButton.setObjectName("SampleWidgetButton")
        self.verticalLayout_5.addWidget(self.SampleWidgetButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 758, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.SampleDialogButton.setText(QtWidgets.QApplication.translate("MainWindow", "OpenSampleDialog", None, -1))
        self.RewindButton.setText(QtWidgets.QApplication.translate("MainWindow", "<<", None, -1))
        self.PlayButton.setText(QtWidgets.QApplication.translate("MainWindow", "Play", None, -1))
        self.PauseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.StopButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.FastForwardButton.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.RecordButton.setText(QtWidgets.QApplication.translate("MainWindow", "Record", None, -1))
        self.SampleWidgetButton.setText(QtWidgets.QApplication.translate("MainWindow", "OpenSampleWidget", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))

